{
  "name": "@stdlib/utils-async-try-catch",
  "version": "0.1.1",
  "description": "If a function does not return an error, invoke a callback with the function result; otherwise, invoke a callback with a value `y`.",
  "license": "Apache-2.0",
  "type": "module",
  "main": "./mod.js",
  "homepage": "https://stdlib.io",
  "repository": {
    "type": "git",
    "url": "git://github.com/stdlib-js/utils-async-try-catch.git"
  },
  "bugs": {
    "url": "https://github.com/stdlib-js/stdlib/issues"
  },
  "keywords": [
    "stdlib",
    "stdutils",
    "stdutil",
    "utilities",
    "utility",
    "utils",
    "util",
    "asynchronous",
    "async",
    "try",
    "catch",
    "try-catch",
    "trap",
    "control",
    "flow",
    "condition",
    "conditional",
    "either-or"
  ],
  "funding": {
    "type": "opencollective",
    "url": "https://opencollective.com/stdlib"
  }
}
